# Generated by Django 5.2.5 on 2025-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='List the primary technologies (e.g., Django, DRF, PostgreSQL)', max_length=250)),
                ('github_url', models.URLField(blank=True, max_length=300, null=True)),
                ('live_demo_url', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
